"""Transparent asynchronous HTTP reverse proxy."""

from __future__ import annotations

from collections.abc import AsyncIterable, Sequence
from typing import Final

import httpx

from ..registry import provider
from .base import (
    BaseProxyComponent,
    ProxyRequestError,
    ProxyResponse,
    ProxyUpstreamError,
    ProxyUpstreamTimeoutError,
)

# These headers describe one transport hop and must be regenerated by httpx or
# Starlette. ``host`` is owned by the selected upstream.
_HOP_BY_HOP_HEADERS: Final = frozenset(
    {
        "connection",
        "host",
        "keep-alive",
        "proxy-authenticate",
        "proxy-authorization",
        "te",
        "trailer",
        "transfer-encoding",
        "upgrade",
    }
)


def _connection_headers(headers: Sequence[tuple[str, str]]) -> set[str]:
    """Return additional hop-by-hop header names declared by Connection."""
    return {
        item.strip().lower()
        for key, value in headers
        if key.lower() == "connection"
        for item in value.split(",")
        if item.strip()
    }


def _request_headers(headers: Sequence[tuple[str, str]]) -> list[tuple[str, str]]:
    """Preserve end-to-end request headers and remove transport-owned ones."""
    excluded = _HOP_BY_HOP_HEADERS | _connection_headers(headers)
    return [(key, value) for key, value in headers if key.lower() not in excluded]


def _response_headers(response: httpx.Response) -> list[tuple[str, str]]:
    """Preserve end-to-end response headers, including repeated fields."""
    pairs = response.headers.multi_items()
    # ``aiter_bytes`` decodes content encodings, so both encoding and the encoded
    # body's length must be regenerated/omitted downstream.
    excluded = (
        _HOP_BY_HOP_HEADERS
        | {"content-encoding", "content-length"}
        | _connection_headers(pairs)
    )
    return [(key, value) for key, value in pairs if key.lower() not in excluded]


def _validate_path(path: str) -> None:
    """Prevent a routed path from escaping the configured upstream prefix."""
    if path and (
        path.startswith("/") or any(part in {".", ".."} for part in path.split("/"))
    ):
        raise ProxyRequestError("Invalid proxy request path")


@provider("http")
class HttpProxyComponent(BaseProxyComponent):
    """Forward unmodified HTTP requests to one fixed upstream base URL."""

    def __init__(
        self,
        upstream_base_url: str,
        timeout: float = 600,
        transport: httpx.AsyncBaseTransport | None = None,
        **kwargs,
    ) -> None:
        super().__init__(**kwargs)
        if not isinstance(upstream_base_url, str) or not upstream_base_url.strip():
            raise ValueError("Proxy upstream_base_url must not be empty")
        if timeout <= 0:
            raise ValueError("Proxy timeout must be greater than 0")

        base_url = upstream_base_url.rstrip("/")
        parsed = httpx.URL(base_url)
        if parsed.scheme not in {"http", "https"} or not parsed.host:
            raise ValueError("Proxy upstream_base_url must be an HTTP(S) URL")

        self.upstream_base_url = base_url
        self.timeout = timeout
        self._transport = transport
        self._client: httpx.AsyncClient | None = None

    async def _start(self) -> None:
        self._client = httpx.AsyncClient(
            base_url=f"{self.upstream_base_url}/",
            timeout=self.timeout,
            transport=self._transport,
        )

    async def _close(self) -> None:
        client, self._client = self._client, None
        if client is not None:
            await client.aclose()

    async def forward(
        self,
        method: str,
        path: str,
        *,
        query: Sequence[tuple[str, str]] = (),
        headers: Sequence[tuple[str, str]] = (),
        content: bytes | AsyncIterable[bytes] = b"",
    ) -> ProxyResponse:
        """Forward method, path, query, end-to-end headers, and body unchanged."""
        client = self._client
        if client is None:
            raise RuntimeError("Proxy component is not running")
        _validate_path(path)

        try:
            request = client.build_request(
                method,
                path,
                params=query,
                headers=_request_headers(headers),
                content=content,
            )
            response = await client.send(request, stream=True)
        except httpx.InvalidURL as exc:
            raise ProxyRequestError("Invalid proxy request path") from exc
        except httpx.TimeoutException as exc:
            raise ProxyUpstreamTimeoutError(
                f"Proxy upstream timed out: {self.upstream_base_url}"
            ) from exc
        except httpx.HTTPError as exc:
            self.logger.warning(f"Proxy upstream request failed: {exc}")
            raise ProxyUpstreamError("Proxy upstream request failed") from exc

        return ProxyResponse(
            status_code=response.status_code,
            content=response.aiter_bytes(),
            headers=_response_headers(response),
            close=response.aclose,
        )
