export const sections = [
  ['getting-started', '开始使用', 'Getting started', ['introduction', 'quickstart', 'studio']],
  [
    'research',
    '量化研究',
    'Quant research',
    ['workflow', 'tushare', 'results', 'backtest', 'strategy-comparison', 'notifications'],
  ],
  [
    'concepts',
    '核心概念',
    'Core concepts',
    ['architecture', 'jobs-and-tasks', 'task-lifecycle', 'task-lineage', 'workspace'],
  ],
  [
    'guides',
    '操作与部署',
    'Operations',
    [
      'task-management',
      'workspace-files',
      'plugin-management',
      'remote-machines',
      'task-sync',
      'scheduling',
      'authentication',
      'deployment',
      'http-proxy',
      'operations',
    ],
  ],
  ['agent', 'Agent', 'Agent', ['configuration', 'usage', 'mcp-integration']],
  [
    'api',
    'API 与事件',
    'API & events',
    ['overview', 'tasks', 'events', 'workspace', 'machines', 'plugins-sync', 'agent'],
  ],
  [
    'reference',
    '配置与协议',
    'Reference',
    [
      'cli',
      'python',
      'configuration',
      'client-configuration',
      'task-contracts',
      'plugin-manifest',
      'research-artifacts',
    ],
  ],
  ['development', '开发与扩展', 'Development', ['framework-extensions', 'studio']],
] as const
